apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordsage-fastapi
  namespace: wordsage
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: fastapi
          image: wordsage-fastapi:latest
          imagePullPolicy: Never