---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordsage-files-pv
  namespace: wordsage
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/data/wordsage-files
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordsage-files-pvc
  namespace: wordsage
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi