version: '3.9'
services:
  wordsage_fastapi:
    build:
      context: ../..
      dockerfile: deploy/docker/Dockerfile.fastapi
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - wordsage_celery_worker
      - prometheus
    volumes:
      - wordsage_files:/wordsage/uploaded_files
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - UPLOAD_DIRECTORY=/wordsage/uploaded_files
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  wordsage_celery_worker:
    build:
      context: ../..
      dockerfile: deploy/docker/Dockerfile.celery_worker
    depends_on:
      - redis
      - prometheus
    volumes:
      - wordsage_files:/wordsage/uploaded_files
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - UPLOAD_DIRECTORY=/wordsage/uploaded_files
    healthcheck:
      test: ["CMD-SHELL", "pgrep celery || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  flower:
    build:
      context: ../..
      dockerfile: deploy/docker/Dockerfile.flower
    ports:
      - "5555:5555"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
      - wordsage_celery_worker
      - prometheus
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5555/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  redis:
    image: redis:6.2
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9090/-/ready || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  redis_exporter:
    image: oliver006/redis_exporter
    environment:
      - REDIS_ADDR=redis:6379
    ports:
      - "9121:9121"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9121/metrics || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/provisioning/dashboards-definitions:/var/lib/grafana/dashboards
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  wordsage_files: