version: '3.9'
services:
  wordsage_fastapi:
    build:
      context: ../..
      dockerfile: deploy/docker/Dockerfile.fastapi
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - wordsage_celery_worker
    volumes:
      - wordsage_files:/wordsage/uploaded_files
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  wordsage_celery_worker:
    build:
      context: ../..
      dockerfile: deploy/docker/Dockerfile.celery_worker
    depends_on:
      - redis
    volumes:
      - wordsage_files:/wordsage/uploaded_files
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -h redis ping | grep PONG || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  flower:
    build:
      context: ../..
      dockerfile: deploy/docker/Dockerfile.flower
    ports:
      - "5555:5555"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
      - wordsage_celery_worker
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5555/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  redis:
    image: redis:6.2
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  wordsage_files: