apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordsage-celery-worker
  namespace: wordsage
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: wordsage-celery-worker
  template:
    metadata:
      labels:
        app: wordsage-celery-worker
    spec:
      containers:
        - name: celery-worker
          image: wordsage-celery-worker:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: wordsage-config
          volumeMounts:
            - name: wordsage-files
              mountPath: /wordsage/uploaded_files
      volumes:
        - name: wordsage-files
          persistentVolumeClaim:
            claimName: wordsage-files-pvc