apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordsage-fastapi-v2
  namespace: wordsage
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: wordsage-fastapi
      version: v2
  template:
    metadata:
      labels:
        app: wordsage-fastapi
        version: v2
    spec:
      containers:
        - name: fastapi
          image: codecrafterm/wordsage-fastapi-v2:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: wordsage-files
              mountPath: /wordsage/uploaded_files
          envFrom:
            - configMapRef:
                name: wordsage-config
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: wordsage-files
          persistentVolumeClaim:
            claimName: wordsage-files-pvc