apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: wordsage
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: prometheus
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'fastapi'
        metrics_path: '/metrics'
        static_configs:
          - targets: ['wordsage-fastapi:8000']

      - job_name: 'redis'
        static_configs:
          - targets: ['redis-exporter:9121']

      - job_name: flower
        static_configs:
          - targets: ['wordsage-flower:5555']