name: CI

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'
        architecture: 'x64'

    - name: Install dependencies
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        poetry install

    - name: Export environment variable for tests
      run: echo "UPLOAD_DIRECTORY=wordsage/uploaded_files" >> $GITHUB_ENV

    - name: Run unit tests
      run: poetry run pytest

    - name: Run linter
      run: poetry run pylint wordsage